version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_TRANSCRIPTION_URL=https://railway.com/project/98030408-897e-4998-9567-c9b4e7edcddb
    depends_on:
      - transcription-api

  transcription-api:
    build: 
      context: ./services/transcription
    ports:
      - "3001:3001" 