version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_TRANSCRIPTION_URL=https://transcription-api-production.up.railway.app
    depends_on:
      - transcription

  transcription:
    build: 
      context: ./services/transcription
    ports:
      - "3001:3001" 