[build]
builder = "nixpacks"
buildCommand = "npm install && npm run clean && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
restartPolicy = "on-failure"
healthcheckTimeout = 300 